config/routes.rb
Junbride::Application.routes.draw do
  resources :guests

  get '', to: 'top#index'
  get '/en', to: 'top#en'
  get '/attend/:code', to: 'top#attend'
  get '/not_attend/:code', to: 'top#not_attend'
  get '/only_1_attend/:code', to: 'top#only_1_attend'
  get '/only_2_attend/:code', to: 'top#only_2_attend'
  get '/get/:code', to: 'top#get_data'
end

app/models/guest.rb
class Guest < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :set_guest, only: [:show, :edit, :update, :destroy]
  before_filter :basic


  # GET /guests
  # GET /guests.json
  def index
    @guests = Guest.all
    render layout: false
  end

  # GET /guests/1
  # GET /guests/1.json
  def show
  end

  # GET /guests/new
  def new
    @guest = Guest.new
  end

  # GET /guests/1/edit
  def edit
  end

  # POST /guests
  # POST /guests.json
  def create
    @guest = Guest.new(guest_params)
    @guest.code = [*100000..999999].sample
    @guest.attendance = 0
    @guest.save

    respond_to do |format|
      if @guest.save
        format.html { redirect_to @guest, notice: 'Guest was successfully created.' }
        format.json { render action: 'show', status: :created, location: @guest }
      else
        format.html { render action: 'new' }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guests/1
  # PATCH/PUT /guests/1.json
  def update
    respond_to do |format|
      if @guest.update(guest_params)
        format.html { redirect_to @guest, notice: 'Guest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1
  # DELETE /guests/1.json
  def destroy
    @guest.destroy
    respond_to do |format|
      format.html { redirect_to guests_url }
      format.json { head :no_content }
    end
  end

  private
    def basic
    authenticate_or_request_with_http_basic do |user, pass|
      user == 'chuniya' && pass == 'chuniya'
    end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_guest
      @guest = Guest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guest_params
      params.require(:guest).permit(:code, :name, :attendance, :message)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index

  end

  def en

  end


  def attend
    code = params[:code].to_i
    @guest = Guest.find_by_code code
    if @guest.present?
      @guest.attendance = 11
      @guest.message = params[:message]
      @guest.save
      render json: @guest
    end
  end
  def not_attend
    code = params[:code].to_i
    @guest = Guest.find_by_code code
    if @guest.present?
      @guest.attendance = 22
      @guest.message = params[:message]
      @guest.save
      render json: @guest
    end
  end
  def only_1_attend
    code = params[:code].to_i
    @guest = Guest.find_by_code code
    if @guest.present?
      @guest.attendance = 12
      @guest.message = params[:message]
      @guest.save
      render json: @guest
    end
  end
  def only_2_attend
    code = params[:code].to_i
    @guest = Guest.find_by_code code
    if @guest.present?
      @guest.attendance = 21
      @guest.message = params[:message]
      @guest.save
      render json: @guest
    end
  end
  def get_data
    code = params[:code].to_i
    @guest = Guest.find_by_code code
    render json: @guest
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/guests/_form.html.erb
<%= form_for(@guest) do |f| %>
  <% if @guest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guest.errors.count, "error") %> prohibited this guest from being saved:</h2>

      <ul>
      <% @guest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :attendance %><br>
    <%= f.text_field :attendance %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guests/edit.html.erb
<h1>Editing guest</h1>

<%= render 'form' %>

<%= link_to 'Show', @guest %> |
<%= link_to 'Back', guests_path %>

app/views/guests/index.html.erb
<h1>Guests</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Attendance</th>
      <th>Message</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @guests.each do |guest| %>
      <tr>
        <td><%= guest.code %></td>
        <td><%= guest.name %></td>
        <td><%= guest.attendance %></td>
        <% if guest.message.nil? %>
        <td></td>
        <% else %>
        <td><%= guest.message.html_safe %></td>
        <% end %>
        <td><%= link_to 'Show', guest %></td>
        <td><%= link_to 'Edit', edit_guest_path(guest) %></td>
        <td><%= link_to 'Destroy', guest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guest', new_guest_path %>

app/views/guests/new.html.erb
<h1>New guest</h1>

<%= render 'form' %>

<%= link_to 'Back', guests_path %>

app/views/guests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @guest.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @guest.name %>
</p>

<p>
  <strong>Attendance:</strong>
  <%= @guest.attendance %>
</p>

<p>
  <strong>Message</strong>
  <%= @guest.message %>
</p>

<%= link_to 'Edit', edit_guest_path(@guest) %> |
<%= link_to 'Back', guests_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>junbri.de</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <script>
    var Chartkick = {"language": "ja"};
  </script>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no">
  <%= csrf_meta_tags %>
  <%= favicon_link_tag "favicon.png" %>
  <link href='http://fonts.googleapis.com/css?family=Crimson+Text' rel='stylesheet' type='text/css'>
</head>
<body>

<%= yield %>
<script src="/my-app.js"></script>
</body>
</html>

app/views/top/attend.html.erb
<p><%= @test %></p>

app/views/top/en.html.erb
<div class="popup popup-about">
  <div class="close-button close-popup">
    <%= image_tag "ast2.png", class: "close-ast", size: "30x30" %>
  </div>
  <div class="pmenu menu1 close-popup">
    <div class="aisatsu">
      <p>
      <div class="info">
        <p class="info-title"><%= image_tag "ast2.png", class: "close-ast", size: "15x15" %>Date & Time<%= image_tag "ast2.png", class: "close-ast", size: "15x15" %></p>
        <br>June 14th<br><br>
        14:40 Please come to the 4th floor of the main building.<br><br>
        15:00 Ceremony<br><br>
        16:00 Reception<br><br>
        <p class="info-title"><%= image_tag "ast2.png", class: "close-ast", size: "15x15" %>Venue<%= image_tag "ast2.png", class: "close-ast", size: "15x15" %></p>
        <br>Happoen Hakuhokan<br>
        1-1-1 Shirokanedai, Minato-ku, Tokyo 108-8631, Japan
      </div>
    </div>
  </div>
  <div class="pmenu menu2 close-popup">
    <div class="aisatsu">
      <p>
      Our concept for the wedding is <%= image_tag "ast2.png", class: "close-ast", size: "15x15" %>.<br>
      As you know, <%= image_tag "ast2.png", class: "close-ast", size: "15x15" %> means multiplication.<br>
      Multiplication often implies "fusion of two things" in Japanese context.<br><br>
      We will prepare many kinds of fusion like fusion of Japanese tradition and modern wedding, Mie and Kyoto (our hometowns), etc.<br><br>
      <%= image_tag "keyboard.jpg", class: "keyboard" %>
      <br><br>If you look at your Mac, <%= image_tag "ast2.png", class: "close-ast", size: "15x15" %> is located on the same key as 8.<br><br>
      Eight is considered to be a lucky number in Japan.<br>
      Coincidentally, August is the birth month of both of us, and eight is also the first kanji of the venue "Happoen (八芳園)"<br><br>
      You will find a lot of things that are shaped like either <%= image_tag "ast2.png", class: "close-ast", size: "15x15" %> or 8 at our wedding.
      </p>
    </div>
  </div>
  <div class="pmenu menu3">
    <div class="list-block">
      <ul>
        <li>
        <div class="item-content">
          <div class="item-inner">
            <div class="item-title label">Your Code</div>
            <div class="item-input">
              <input class="invite" type="text" placeholder="Input 6 digit number">
            </div>
          </div>
        </div>
        </li>
        <li>
        <div class="item-content">
          <div class="item-inner">
            <div class="item-title label guest"></div>
            <div class="item-input">
              <input class="guest-name" type="text" placeholder="">
            </div>
          </div>
        </div>
        </li>
        <li>
        <div class="item-content">
          <div class="item-inner">
            <div class="item-title label">Ceremony</div>
            <div class="item-input">
              <label class="label-switch">
                <input class="attend1" type="checkbox">
                <div class="checkbox"></div>
              </label>
            </div>
          </div>
        </div>
        </li>
        <li>
        <div class="item-content">
          <div class="item-inner">
            <div class="item-title label">Reception</div>
            <div class="item-input">
              <label class="label-switch">
                <input class="attend2" type="checkbox">
                <div class="checkbox"></div>
              </label>
            </div>
          </div>
        </div>
        </li>
        <li>
        <div class="item-content">
          <div class="item-inner">
            <div class="item-title label">Message</div>
            <div class="item-input">
              <textarea class="message" placeholder="If you are alergic to any food, please mention it here." col="100" style="font-size: 90%; max-width: 100%;"></textarea>
            </div>
          </div>
        </div>
        </li>
        <p class="my-button submit">Submit</p>
      </ul>
    </div>
  </div>
</div>

<div class="panel-overlay"></div>

<!-- Left Panel with Reveal effect -->
<div class="panel panel-left panel-reveal">
  <div class="content-block">
    <ul class="menu">
      <li id="1" class="open-popup border">Date and Time</li>
      <li id="2" class="open-popup border">Concept</li>
      <li id="3" class="open-popup border">Attendance</li>
      <a target="_blank" href="http://happo-en.com/english/access/index.html">
        <li>
        Access
        </li>
      </a>
    </ul>
    <div class="keyboard">
      <div><%= image_tag "ast1.png", size: "50x50" %></div>
      <div><%= image_tag "8.png", size: "50x50" %></div>
    </div>
  </div>
</div>

<div class="views">
  <div class="view view-main">
    <div class="page-content">
      <div class="content-block open-panel">
        <div class="top">
          <div class="top1">
            <p>JUNE BRI.DE</p>
          </div>
          <div class="top2">
            <p>JUNE 14TH 2015</p>
          </div>
          <div class="top3">
            <p>HAPPOEN</p>
          </div>
        </div>
        <div class="menu-button open-panel">
          <div class="line"></div>
          <div class="line"></div>
          <div class="line"></div>
        </div>
        <div class="names">
          <p class="left">TAKAHIDE</p>
          <p class="right">MISATO</p>
        </div>
        <div class="chu" style="font-size: 65%;">
          We will not look like this. It is a Japanese traditional wedding.
        </div>
        <div class="top4 open-panel">
          <p class="click-here">CLICK HERE!</p>
        </div>
        <%= image_tag "kekkon.png", class: "top-image" %>
        <%= image_tag "kekkon_black.png", class: "top-image black" %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
$(".page-content").snowfall({
flakeCount :20, // 数
flakeIndex : 99999, // スタイルシートのz-indexの値
maxSpeed : 3, // 最大速度
minSpeed : 1, // 最小速度
maxSize  : 20, // 最大サイズ
minSize  : 1, // 最小サイズ
image : '/images/ast1.png'
});
</script>

app/views/top/index.html.erb
<div class="popup popup-about">
  <div class="close-button close-popup">
    <%= image_tag "ast2.png", class: "close-ast", size: "30x30" %>
  </div>
  <div class="pmenu menu1 close-popup">
    <div class="aisatsu">
      <p>
      拝啓　春陽の候<br>皆様におかれましては益々ご健勝のこととお慶び申し上げます<br>
      私たちは平成26年11月11日に入籍し 新生活をスタートさせました<br>
      つきましては ご挨拶を兼ねまして ささやかですが小宴を催したいと存じます<br>
      ご多用中 誠に恐縮ではございますが ぜひご出席をいただきたく ご案内申し上げます</p>
      <p class="keigu">敬具</p>
      <div class="info">
        <p class="info-title"><%= image_tag "ast2.png", class: "close-ast", size: "15x15" %>日時<%= image_tag "ast2.png", class: "close-ast", size: "15x15" %></p>
        平成27年6月14日(日)<br>
        集　合　　14時40分<br>
        （本館4階控え室）<br><br>
        挙　式　　15時00分<br>
        披露宴　　16時00分<br><br>
        <p class="info-title"><%= image_tag "ast2.png", class: "close-ast", size: "15x15" %>会場<%= image_tag "ast2.png", class: "close-ast", size: "15x15" %></p>
        八芳園 白鳳館<br>
        東京都港区白金台1-1-1
      </div>
      <p>平成27年4月吉日</p>
      <p style="text-align: right;">
      細川貴英<br>
      吉田美里</p>
    </div>
  </div>
  <div class="pmenu menu2 close-popup">
    <div class="aisatsu">
      <p>
      私たちふたりが<br>
      結婚式に選んだコンセプトは<br>
      <%= image_tag "ast2.png", class: "close-ast", size: "15x15" %> 
      （スター）です<br><br>
      かけ算の意味があるこの記号は<br>
      あらゆるものの融合を表します<br><br>
      和と洋のかけ算<br>
      三重と京都のかけ算など<br>
      当日はさまざまなものの融合を<br>
      お楽しみいただけるよう<br>
      精一杯のおもてなしを<br>
      させていただく予定です<br><br>
      <%= image_tag "keyboard.jpg", class: "keyboard" %>
      <br><br>キーボードを見たら<br>
      たまたま
      <%= image_tag "ast2.png", class: "close-ast", size: "15x15" %> 
      は８と同じ<br>
      場所にありました<br><br>
      ふたりの誕生月である８<br>
      八芳園の頭文字でもある８は<br>
      漢字にすれば八（末広がり）<br>
      横にすれば∞（無限大）と<br>
      何かと縁起の良い数字です<br><br>
      当日はいたるところに<br>
      スターや８を散りばめた<br>
      いろんなものの「かけ算」を<br>
      お楽しみください<br>
      </p>
    </div>
  </div>
  <div class="pmenu menu3">
    <div class="list-block">
      <ul>
        <li>
        <div class="item-content">
          <div class="item-inner">
            <div class="item-title label">コード</div>
            <div class="item-input">
              <input class="invite" type="text" placeholder="6桁の数字を入力">
            </div>
          </div>
        </div>
        </li>
        <li>
        <div class="item-content">
          <div class="item-inner">
            <div class="item-title label guest"></div>
            <div class="item-input">
              <input class="guest-name" type="text" placeholder="">
            </div>
          </div>
        </div>
        </li>
        <li>
        <div class="item-content">
          <div class="item-inner">
            <div class="item-title label">挙式出欠</div>
            <div class="item-input">
              <label class="label-switch">
                <input class="attend1" type="checkbox">
                <div class="checkbox"></div>
              </label>
            </div>
          </div>
        </div>
        </li>
        <li>
        <div class="item-content">
          <div class="item-inner">
            <div class="item-title label">披露宴出欠</div>
            <div class="item-input">
              <label class="label-switch">
                <input class="attend2" type="checkbox">
                <div class="checkbox"></div>
              </label>
            </div>
          </div>
        </div>
        </li>
        <li>
        <div class="item-content">
          <div class="item-inner">
            <div class="item-title label">メッセージ</div>
            <div class="item-input">
              <textarea class="message" placeholder="アレルギー食材等あれば、ここに書いてください。" col="100" style="font-size: 90%; max-width: 100%;"></textarea>
            </div>
          </div>
        </div>
        </li>
        <p class="my-button submit">送信</p>
      </ul>
    </div>
  </div>
</div>

<div class="panel-overlay"></div>

<!-- Left Panel with Reveal effect -->
<div class="panel panel-left panel-reveal">
  <div class="content-block">
    <ul class="menu">
      <li id="1" class="open-popup border">ごあいさつ</li>
      <li id="2" class="open-popup border">コンセプト</li>
      <li id="3" class="open-popup border">出席確認</li>
      <a target="_blank" href="http://www.happo-en.com/access/">
        <li>
        会場地図
        </li>
      </a>
    </ul>
    <div class="keyboard">
      <div><%= image_tag "ast1.png", size: "50x50" %></div>
      <div><%= image_tag "8.png", size: "50x50" %></div>
    </div>
    <a href="http://lastage.info/redirect.html" style="position: absolute; left: 30px; bottom: 30px; color: #fff;">
      English
    </a>
  </div>
</div>

<div class="views">
  <div class="view view-main">
    <div class="page-content">
      <div class="content-block open-panel">
        <div class="top">
          <div class="top1">
            <p>JUNE BRI.DE</p>
          </div>
          <div class="top2">
            <p>JUNE 14TH 2015</p>
          </div>
          <div class="top3">
            <p>HAPPOEN</p>
          </div>
        </div>
        <div class="menu-button open-panel">
          <div class="line"></div>
          <div class="line"></div>
          <div class="line"></div>
        </div>
        <div class="names">
          <p class="left">TAKAHIDE</p>
          <p class="right">MISATO</p>
        </div>
        <div class="chu">
          <p>※ 当日は、和婚です。</p>
        </div>
        <div class="top4 open-panel">
          <p class="click-here">CLICK HERE!</p>
        </div>
        <%= image_tag "kekkon.png", class: "top-image" %>
        <%= image_tag "kekkon_black.png", class: "top-image black" %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
$(".page-content").snowfall({
flakeCount :20, // 数
flakeIndex : 99999, // スタイルシートのz-indexの値
maxSpeed : 3, // 最大速度
minSpeed : 1, // 最小速度
maxSize  : 20, // 最大サイズ
minSize  : 1, // 最小サイズ
image : '/images/ast1.png'
});
</script>

app/views/top/not_attend.html.erb
<p></p>